external_components:
  - source: components

esphome:
  name: amg8833
  platform: ESP8266
  board: d1_mini
  libraries:
    - "TheRealWaldo/SparkFun GridEYE AMG88 Library"

wifi:
  ssid: !secret ssid
  password: !secret password
  domain: !secret domain

logger:

api:

ota:

i2c:

amg8833:

text_sensor:
  - platform: amg8833
    camera_sensor:
      name: "Sensor Pixels"

binary_sensor:
  - platform: amg8833
    name: "Person Detected"

sensor:
  - platform: amg8833
    id: blank
    sensor_temp:
      name: "Thermal Sensor Temperature"
    max_temp:
      name: "Thermal Sensor Max"
    min_temp:
      name: "Thermal Sensor Min"
    avg_temp:
      name: "Thermal Sensor Avg"
    min_index:
      name: "Thermal Sensor Min Index"
    max_index:
      name: "Thermal Sensor Max Index"
